//
// ChannelAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ChannelAPI: APIBase {
    /**
     频道列表
     
     - parameter s: (query) 否(默认 1) 上线状态，0 或 1 (optional, default to 1)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsChsGet(s s: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsChsGetWithRequestBuilder(s: s).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     频道列表
     - GET /ns/chs
     - 从服务器获取 频道的列表
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter s: (query) 否(默认 1) 上线状态，0 或 1 (optional, default to 1)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsChsGetWithRequestBuilder(s s: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/ns/chs"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "s": s
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
