//
// CommentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CommentAPI: APIBase {
    /**
     新闻普通评论列表
     
     - parameter did: (query) 新闻 docid 
     - parameter uid: (query) 注册用户ID，提供该ID会在响应中设置该用户的点赞标记 upflag (optional)
     - parameter p: (query) 新闻ID (optional, default to 1)
     - parameter c: (query) 新闻ID (optional, default to 20)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsComsCGet(did did: String, uid: String? = nil, p: String? = nil, c: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsComsCGetWithRequestBuilder(did: did, uid: uid, p: p, c: c).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     新闻普通评论列表
     - GET /ns/coms/c
     - 从服务器获取 新闻普通评论列表
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter did: (query) 新闻 docid 
     - parameter uid: (query) 注册用户ID，提供该ID会在响应中设置该用户的点赞标记 upflag (optional)
     - parameter p: (query) 新闻ID (optional, default to 1)
     - parameter c: (query) 新闻ID (optional, default to 20)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsComsCGetWithRequestBuilder(did did: String, uid: String? = nil, p: String? = nil, c: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/ns/coms/c"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "did": did,
            "uid": uid,
            "p": p,
            "c": c
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     新闻热点评论列表
     
     - parameter did: (query) 新闻 docid 
     - parameter uid: (query) 注册用户ID，提供该ID会在响应中设置该用户的点赞标记 upflag (optional)
     - parameter p: (query) 新闻ID (optional, default to 1)
     - parameter c: (query) 新闻ID (optional, default to 20)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsComsHGet(did did: String, uid: String? = nil, p: String? = nil, c: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsComsHGetWithRequestBuilder(did: did, uid: uid, p: p, c: c).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     新闻热点评论列表
     - GET /ns/coms/h
     - 从服务器获取 新闻热点评论列表
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter did: (query) 新闻 docid 
     - parameter uid: (query) 注册用户ID，提供该ID会在响应中设置该用户的点赞标记 upflag (optional)
     - parameter p: (query) 新闻ID (optional, default to 1)
     - parameter c: (query) 新闻ID (optional, default to 20)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsComsHGetWithRequestBuilder(did did: String, uid: String? = nil, p: String? = nil, c: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/ns/coms/h"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "did": did,
            "uid": uid,
            "p": p,
            "c": c
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
