//
// NewAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class NewAPI: APIBase {
    /**
     新闻-列表页加载
     
     - parameter nid: (query) 新闻ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsConGet(nid nid: String, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsConGetWithRequestBuilder(nid: nid).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     新闻-列表页加载
     - GET /ns/con
     - 从服务器获取 新闻-列表页加载
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter nid: (query) 新闻ID 

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsConGetWithRequestBuilder(nid nid: String) -> RequestBuilder<AnyObject> {
        let path = "/ns/con"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "nid": nid
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     新闻-列表页加载
     
     - parameter cid: (query) 频道id 
     - parameter tcr: (query) 起始时间，13位时间戳 
     - parameter p: (query) 页数 (optional, default to 1)
     - parameter c: (query) 条数 (optional, default to 20)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsFedLGet(cid cid: String, tcr: String, p: String? = nil, c: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsFedLGetWithRequestBuilder(cid: cid, tcr: tcr, p: p, c: c).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     新闻-列表页加载
     - GET /ns/fed/l
     - 从服务器获取 新闻-列表页加载
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter cid: (query) 频道id 
     - parameter tcr: (query) 起始时间，13位时间戳 
     - parameter p: (query) 页数 (optional, default to 1)
     - parameter c: (query) 条数 (optional, default to 20)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsFedLGetWithRequestBuilder(cid cid: String, tcr: String, p: String? = nil, c: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/ns/fed/l"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "cid": cid,
            "tcr": tcr,
            "p": p,
            "c": c
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     新闻-列表页刷新
     
     - parameter cid: (query) 频道id 
     - parameter tcr: (query) 起始时间，13位时间戳 
     - parameter p: (query) 页数 (optional, default to 1)
     - parameter c: (query) 条数 (optional, default to 20)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func nsFedRGet(cid cid: String, tcr: String, p: String? = nil, c: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        nsFedRGetWithRequestBuilder(cid: cid, tcr: tcr, p: p, c: c).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     新闻-列表页刷新
     - GET /ns/fed/r
     - 从服务器获取 新闻-列表页刷新
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter cid: (query) 频道id 
     - parameter tcr: (query) 起始时间，13位时间戳 
     - parameter p: (query) 页数 (optional, default to 1)
     - parameter c: (query) 条数 (optional, default to 20)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func nsFedRGetWithRequestBuilder(cid cid: String, tcr: String, p: String? = nil, c: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/ns/fed/r"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "cid": cid,
            "tcr": tcr,
            "p": p,
            "c": c
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
