//
// UserAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class UserAPI: APIBase {
    /**
     
     \u6E38\u5BA2\u7528\u6237\u767B\u5F55
     
     - parameter userLoginInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func auLinGPost(userLoginInfo userLoginInfo: VisitorsLogin, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        auLinGPostWithRequestBuilder(userLoginInfo: userLoginInfo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u6E38\u5BA2\u7528\u6237\u767B\u5F55
     
     - POST /au/lin/g
     - \u5411\u670D\u52A1\u5668\u767B\u9646\u4E00\u4E2A\u6E38\u5BA2
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter userLoginInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 

     - returns: RequestBuilder<AnyObject> 
     */
    public class func auLinGPostWithRequestBuilder(userLoginInfo userLoginInfo: VisitorsLogin) -> RequestBuilder<AnyObject> {
        let path = "/au/lin/g"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = userLoginInfo.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     \u6E38\u5BA2\u7528\u6237\u6CE8\u518C
     
     - parameter userRegisterInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func auSinGPost(userRegisterInfo userRegisterInfo: VisitorsRegister, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        auSinGPostWithRequestBuilder(userRegisterInfo: userRegisterInfo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u6E38\u5BA2\u7528\u6237\u6CE8\u518C
     
     - POST /au/sin/g
     - \u60F3\u670D\u52A1\u5668\u6CE8\u518C\u4E00\u4E2A\u7528\u4E8E\u57FA\u672C\u6D4F\u89C8\u7684\u6E38\u5BA2\u7528\u6237
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter userRegisterInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 

     - returns: RequestBuilder<AnyObject> 
     */
    public class func auSinGPostWithRequestBuilder(userRegisterInfo userRegisterInfo: VisitorsRegister) -> RequestBuilder<AnyObject> {
        let path = "/au/sin/g"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = userRegisterInfo.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     \u7B2C\u4E09\u65B9\u7528\u6237\u6CE8\u518C
     
     - parameter userRegisterInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func auSinSPost(userRegisterInfo userRegisterInfo: UserRegister, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        auSinSPostWithRequestBuilder(userRegisterInfo: userRegisterInfo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     \u7B2C\u4E09\u65B9\u7528\u6237\u6CE8\u518C
     
     - POST /au/sin/s
     - \u5411\u670D\u52A1\u5668\u6CE8\u518C\u7B2C\u4E09\u65B9\u7528\u6237
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter userRegisterInfo: (body) \u7528\u6237\u6CE8\u518C\u4FE1\u606F 

     - returns: RequestBuilder<AnyObject> 
     */
    public class func auSinSPostWithRequestBuilder(userRegisterInfo userRegisterInfo: UserRegister) -> RequestBuilder<AnyObject> {
        let path = "/au/sin/s"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = userRegisterInfo.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

}
