// APIHelper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

class APIHelper {
    static func rejectNil(_ source: [String:AnyObject?]) -> [String:AnyObject]? {
        var destination = [String:AnyObject]()
        for (key, nillableValue) in source {
            if let value: AnyObject = nillableValue {
                destination[key] = value
            }
        }

        if destination.isEmpty {
            return nil
        }
        return destination
    }

    static func convertBoolToString(_ source: [String: AnyObject]?) -> [String:AnyObject] {
        var destination = [String:AnyObject]()
        let theTrue = NSNumber(value: true as Bool)
        let theFalse = NSNumber(value: false as Bool)
        if (source != nil) {
            for (key, value) in source! {
                switch value {
                    case let x where x === theTrue || x === theFalse:
                        destination[key] = "\(value as! Bool)" as AnyObject?
                    default:
                        destination[key] = value
                }
            }
        }
        return destination
    }

}
