// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T

    public init(statusCode: Int, header: [String: String], body: T) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()
    
    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }
    
    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }
    
    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictinoary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictinoary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }
    
    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if source is T {
            return source as! T
        }
        
        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }
	
    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.dateFromString(sourceString) {
                            return date
                        }
                    }
                
                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return NSDate(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            } 

			// Decoder for [Channel]
            Decoders.addDecoder(clazz: [Channel].self) { (source: AnyObject) -> [Channel] in
                return Decoders.decode(clazz: [Channel].self, source: source)
            }
			// Decoder for Channel
            Decoders.addDecoder(clazz: Channel.self) { (source: AnyObject) -> Channel in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Channel()
                instance.code = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["code"])
                instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"])
                instance.data = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["data"])
                return instance
            }
			

			// Decoder for [ChannelData]
            Decoders.addDecoder(clazz: [ChannelData].self) { (source: AnyObject) -> [ChannelData] in
                return Decoders.decode(clazz: [ChannelData].self, source: source)
            }
			// Decoder for ChannelData
            Decoders.addDecoder(clazz: ChannelData.self) { (source: AnyObject) -> ChannelData in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = ChannelData()
                instance.cname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["cname"])
                instance.online = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["online"])
                instance.id = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["id"])
                return instance
            }
			

			// Decoder for [News]
            Decoders.addDecoder(clazz: [News].self) { (source: AnyObject) -> [News] in
                return Decoders.decode(clazz: [News].self, source: source)
            }
			// Decoder for News
            Decoders.addDecoder(clazz: News.self) { (source: AnyObject) -> News in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = News()
                instance.code = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["code"])
                instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"])
                instance.data = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["data"])
                return instance
            }
			

			// Decoder for [NewsData]
            Decoders.addDecoder(clazz: [NewsData].self) { (source: AnyObject) -> [NewsData] in
                return Decoders.decode(clazz: [NewsData].self, source: source)
            }
			// Decoder for NewsData
            Decoders.addDecoder(clazz: NewsData.self) { (source: AnyObject) -> NewsData in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = NewsData()
                instance.pubName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pubName"])
                instance.imgStyle = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["imgStyle"])
                instance.city = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["city"])
                instance.docid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["docid"])
                instance.pubTime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pubTime"])
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"])
                instance.url = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["url"])
                instance.pubUrl = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pubUrl"])
                instance.province = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["province"])
                instance.commentsCount = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["commentsCount"])
                instance.district = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["district"])
                instance.channelId = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["channelId"])
                instance.imgList = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["imgList"])
                return instance
            }
			
        }
    }
}
