// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

open class Response<T> {
    open let statusCode: Int
    open let header: [String: String]
    open let body: T

    public init(statusCode: Int, header: [String: String], body: T) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: HTTPURLResponse, body: T) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = Int()
class Decoders {
    private static var __once: () = {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'"
            ].map { (format: String) -> DateFormatter in
                let formatter = DateFormatter()
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: Date.self) { (source: AnyObject) -> Date in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.date(from: sourceString) {
                            return date
                        }
                    }
                
                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return Date(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            } 

            // Decoder for [Aboutnews]
            Decoders.addDecoder(clazz: [Aboutnews].self) { (source: AnyObject) -> [Aboutnews] in
                return Decoders.decode(clazz: [Aboutnews].self, source: source)
            }
            // Decoder for Aboutnews
            Decoders.addDecoder(clazz: Aboutnews.self) { (source: AnyObject) -> Aboutnews in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = Aboutnews()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [AboutnewsData]
            Decoders.addDecoder(clazz: [AboutnewsData].self) { (source: AnyObject) -> [AboutnewsData] in
                return Decoders.decode(clazz: [AboutnewsData].self, source: source)
            }
            // Decoder for AboutnewsData
            Decoders.addDecoder(clazz: AboutnewsData.self) { (source: AnyObject) -> AboutnewsData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = AboutnewsData()
                instance.url = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["url"] as AnyObject?)
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"] as AnyObject?)
                instance.from = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["from"] as AnyObject?)
                instance.rank = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["rank"] as AnyObject?)
                instance.ptime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ptime"] as AnyObject?)
                instance.pname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pname"] as AnyObject?)
                instance.img = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["img"] as AnyObject?)
                instance.abs = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["abs"] as AnyObject?)
                return instance
            }


            // Decoder for [Channels]
            Decoders.addDecoder(clazz: [Channels].self) { (source: AnyObject) -> [Channels] in
                return Decoders.decode(clazz: [Channels].self, source: source)
            }
            // Decoder for Channels
            Decoders.addDecoder(clazz: Channels.self) { (source: AnyObject) -> Channels in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = Channels()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: ChannelsData.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [ChannelsData]
            Decoders.addDecoder(clazz: [ChannelsData].self) { (source: AnyObject) -> [ChannelsData] in
                return Decoders.decode(clazz: [ChannelsData].self, source: source)
            }
            // Decoder for ChannelsData
            Decoders.addDecoder(clazz: ChannelsData.self) { (source: AnyObject) -> ChannelsData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = ChannelsData()
                instance.id = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["id"] as AnyObject?)
                instance.cname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["cname"] as AnyObject?)
                instance.state = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["state"] as AnyObject?)
                return instance
            }


            // Decoder for [CommectCreate]
            Decoders.addDecoder(clazz: [CommectCreate].self) { (source: AnyObject) -> [CommectCreate] in
                return Decoders.decode(clazz: [CommectCreate].self, source: source)
            }
            // Decoder for CommectCreate
            Decoders.addDecoder(clazz: CommectCreate.self) { (source: AnyObject) -> CommectCreate in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = CommectCreate()
                instance.content = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["content"] as AnyObject?)
                instance.commend = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["commend"] as AnyObject?)
                instance.ctime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ctime"] as AnyObject?)
                instance.uid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["uid"] as AnyObject?)
                instance.uname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uname"] as AnyObject?)
                instance.avatar = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["avatar"] as AnyObject?)
                instance.docid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["docid"] as AnyObject?)
                return instance
            }


            // Decoder for [CommentRespone]
            Decoders.addDecoder(clazz: [CommentRespone].self) { (source: AnyObject) -> [CommentRespone] in
                return Decoders.decode(clazz: [CommentRespone].self, source: source)
            }
            // Decoder for CommentRespone
            Decoders.addDecoder(clazz: CommentRespone.self) { (source: AnyObject) -> CommentRespone in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = CommentRespone()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [Comments]
            Decoders.addDecoder(clazz: [Comments].self) { (source: AnyObject) -> [Comments] in
                return Decoders.decode(clazz: [Comments].self, source: source)
            }
            // Decoder for Comments
            Decoders.addDecoder(clazz: Comments.self) { (source: AnyObject) -> Comments in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = Comments()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [CommentsData]
            Decoders.addDecoder(clazz: [CommentsData].self) { (source: AnyObject) -> [CommentsData] in
                return Decoders.decode(clazz: [CommentsData].self, source: source)
            }
            // Decoder for CommentsData
            Decoders.addDecoder(clazz: CommentsData.self) { (source: AnyObject) -> CommentsData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = CommentsData()
                instance.id = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["id"] as AnyObject?)
                instance.content = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["content"] as AnyObject?)
                instance.commend = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["commend"] as AnyObject?)
                instance.ctime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ctime"] as AnyObject?)
                instance.uid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["uid"] as AnyObject?)
                instance.uname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uname"] as AnyObject?)
                instance.avatar = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["avatar"] as AnyObject?)
                instance.docid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["docid"] as AnyObject?)
                instance.upflag = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["upflag"] as AnyObject?)
                return instance
            }


            // Decoder for [Newinfo]
            Decoders.addDecoder(clazz: [Newinfo].self) { (source: AnyObject) -> [Newinfo] in
                return Decoders.decode(clazz: [Newinfo].self, source: source)
            }
            // Decoder for Newinfo
            Decoders.addDecoder(clazz: Newinfo.self) { (source: AnyObject) -> Newinfo in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = Newinfo()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: NewinfoData.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [NewinfoData]
            Decoders.addDecoder(clazz: [NewinfoData].self) { (source: AnyObject) -> [NewinfoData] in
                return Decoders.decode(clazz: [NewinfoData].self, source: source)
            }
            // Decoder for NewinfoData
            Decoders.addDecoder(clazz: NewinfoData.self) { (source: AnyObject) -> NewinfoData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = NewinfoData()
                instance.nid = Decoders.decodeOptional(clazz: Int64.self, source: sourceDictionary["nid"] as AnyObject?)
                instance.url = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["url"] as AnyObject?)
                instance.docid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["docid"] as AnyObject?)
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"] as AnyObject?)
                instance.ptime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ptime"] as AnyObject?)
                instance.pname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pname"] as AnyObject?)
                instance.purl = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["purl"] as AnyObject?)
                instance.channel = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["channel"] as AnyObject?)
                instance.collect = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["collect"] as AnyObject?)
                instance.concern = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["concern"] as AnyObject?)
                instance.comment = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["comment"] as AnyObject?)
                instance.inum = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["inum"] as AnyObject?)
                instance.tags = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["tags"] as AnyObject?)
                instance.content = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["content"] as AnyObject?)
                return instance
            }


            // Decoder for [NewinfoDataContent]
            Decoders.addDecoder(clazz: [NewinfoDataContent].self) { (source: AnyObject) -> [NewinfoDataContent] in
                return Decoders.decode(clazz: [NewinfoDataContent].self, source: source)
            }
            // Decoder for NewinfoDataContent
            Decoders.addDecoder(clazz: NewinfoDataContent.self) { (source: AnyObject) -> NewinfoDataContent in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = NewinfoDataContent()
                instance.txt = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["txt"] as AnyObject?)
                instance.img = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["img"] as AnyObject?)
                instance.vid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["vid"] as AnyObject?)
                return instance
            }


            // Decoder for [News]
            Decoders.addDecoder(clazz: [News].self) { (source: AnyObject) -> [News] in
                return Decoders.decode(clazz: [News].self, source: source)
            }
            // Decoder for News
            Decoders.addDecoder(clazz: News.self) { (source: AnyObject) -> News in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = News()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: NewsData.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [NewsData]
            Decoders.addDecoder(clazz: [NewsData].self) { (source: AnyObject) -> [NewsData] in
                return Decoders.decode(clazz: [NewsData].self, source: source)
            }
            // Decoder for NewsData
            Decoders.addDecoder(clazz: NewsData.self) { (source: AnyObject) -> NewsData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = NewsData()
                instance.nid = Decoders.decodeOptional(clazz: Int64.self, source: sourceDictionary["nid"] as AnyObject?)
                instance.url = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["url"] as AnyObject?)
                instance.docid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["docid"] as AnyObject?)
                instance.title = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["title"] as AnyObject?)
                instance.ptime = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ptime"] as AnyObject?)
                instance.pname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["pname"] as AnyObject?)
                instance.purl = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["purl"] as AnyObject?)
                instance.channel = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["channel"] as AnyObject?)
                instance.collect = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["collect"] as AnyObject?)
                instance.concern = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["concern"] as AnyObject?)
                instance.comment = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["comment"] as AnyObject?)
                instance.style = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["style"] as AnyObject?)
                instance.province = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["province"] as AnyObject?)
                instance.city = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["city"] as AnyObject?)
                instance.district = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["district"] as AnyObject?)
                instance.imgs = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["imgs"] as AnyObject?)
                return instance
            }


            // Decoder for [User]
            Decoders.addDecoder(clazz: [User].self) { (source: AnyObject) -> [User] in
                return Decoders.decode(clazz: [User].self, source: source)
            }
            // Decoder for User
            Decoders.addDecoder(clazz: User.self) { (source: AnyObject) -> User in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = User()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: UserData.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [UserData]
            Decoders.addDecoder(clazz: [UserData].self) { (source: AnyObject) -> [UserData] in
                return Decoders.decode(clazz: [UserData].self, source: source)
            }
            // Decoder for UserData
            Decoders.addDecoder(clazz: UserData.self) { (source: AnyObject) -> UserData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = UserData()
                instance.utype = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["utype"] as AnyObject?)
                instance.uid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["uid"] as AnyObject?)
                instance.uname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uname"] as AnyObject?)
                instance.avatar = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["avatar"] as AnyObject?)
                instance.password = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["password"] as AnyObject?)
                instance.channel = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["channel"] as AnyObject?)
                return instance
            }


            // Decoder for [UserRegister]
            Decoders.addDecoder(clazz: [UserRegister].self) { (source: AnyObject) -> [UserRegister] in
                return Decoders.decode(clazz: [UserRegister].self, source: source)
            }
            // Decoder for UserRegister
            Decoders.addDecoder(clazz: UserRegister.self) { (source: AnyObject) -> UserRegister in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = UserRegister()
                instance.muid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["muid"] as AnyObject?)
                instance.msuid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["msuid"] as AnyObject?)
                instance.utype = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["utype"] as AnyObject?)
                instance.platform = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["platform"] as AnyObject?)
                instance.suid = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["suid"] as AnyObject?)
                instance.stoken = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["stoken"] as AnyObject?)
                instance.sexpires = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["sexpires"] as AnyObject?)
                instance.uname = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uname"] as AnyObject?)
                instance.gender = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["gender"] as AnyObject?)
                instance.avatar = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["avatar"] as AnyObject?)
                instance.averse = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["averse"] as AnyObject?)
                instance.prefer = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["prefer"] as AnyObject?)
                instance.province = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["province"] as AnyObject?)
                instance.city = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["city"] as AnyObject?)
                instance.district = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["district"] as AnyObject?)
                return instance
            }


            // Decoder for [VisitorsLogin]
            Decoders.addDecoder(clazz: [VisitorsLogin].self) { (source: AnyObject) -> [VisitorsLogin] in
                return Decoders.decode(clazz: [VisitorsLogin].self, source: source)
            }
            // Decoder for VisitorsLogin
            Decoders.addDecoder(clazz: VisitorsLogin.self) { (source: AnyObject) -> VisitorsLogin in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = VisitorsLogin()
                instance.uid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["uid"] as AnyObject?)
                instance.password = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["password"] as AnyObject?)
                return instance
            }


            // Decoder for [VisitorsRegister]
            Decoders.addDecoder(clazz: [VisitorsRegister].self) { (source: AnyObject) -> [VisitorsRegister] in
                return Decoders.decode(clazz: [VisitorsRegister].self, source: source)
            }
            // Decoder for VisitorsRegister
            Decoders.addDecoder(clazz: VisitorsRegister.self) { (source: AnyObject) -> VisitorsRegister in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = VisitorsRegister()
                instance.utype = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["utype"] as AnyObject?)
                instance.platform = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["platform"] as AnyObject?)
                instance.province = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["province"] as AnyObject?)
                instance.city = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["city"] as AnyObject?)
                instance.district = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["district"] as AnyObject?)
                return instance
            }


            // Decoder for [VisitorsUser]
            Decoders.addDecoder(clazz: [VisitorsUser].self) { (source: AnyObject) -> [VisitorsUser] in
                return Decoders.decode(clazz: [VisitorsUser].self, source: source)
            }
            // Decoder for VisitorsUser
            Decoders.addDecoder(clazz: VisitorsUser.self) { (source: AnyObject) -> VisitorsUser in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = VisitorsUser()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"] as AnyObject?)
                instance.data = Decoders.decodeOptional(clazz: VisitorsUserData.self, source: sourceDictionary["data"] as AnyObject?)
                return instance
            }


            // Decoder for [VisitorsUserData]
            Decoders.addDecoder(clazz: [VisitorsUserData].self) { (source: AnyObject) -> [VisitorsUserData] in
                return Decoders.decode(clazz: [VisitorsUserData].self, source: source)
            }
            // Decoder for VisitorsUserData
            Decoders.addDecoder(clazz: VisitorsUserData.self) { (source: AnyObject) -> VisitorsUserData in
                let sourceDictionary = source as! [AnyHashable: Any]
                let instance = VisitorsUserData()
                instance.utype = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["utype"] as AnyObject?)
                instance.uid = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["uid"] as AnyObject?)
                instance.password = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["password"] as AnyObject?)
                instance.channel = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["channel"] as AnyObject?)
                return instance
            }
        }()
    static fileprivate var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()
    
    static func addDecoder<T>(clazz: T.Type, decoder: @escaping ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as AnyObject }
    }
    
    static func decode<T>(clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }
    
    static func decode<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }
    
    static func decode<T>(clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.int32Value as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.int64Value as! T;
        }
        if source is T {
            return source as! T
        }
        
        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }
	
    static fileprivate func initialize() {
        _ = Decoders.__once
    }
}
