//
// AboutnewsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AboutnewsData: JSONEncodable {
    /** 新闻地址 */
    open var url: String?
    /** 新闻标题 */
    open var title: String?
    /** 新闻来源 */
    open var from: String?
    /** 赞数 */
    open var rank: Int32?
    /** 创建时间 */
    open var ptime: String?
    /** 来源地址 */
    open var pname: String?
    /** 图片地址 */
    open var img: String?
    /** 描述 */
    open var abs: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["url"] = self.url as AnyObject??
        nillableDictionary["title"] = self.title as AnyObject??
        nillableDictionary["from"] = self.from as AnyObject??
        nillableDictionary["rank"] = self.rank?.encodeToJSON()
        nillableDictionary["ptime"] = self.ptime as AnyObject??
        nillableDictionary["pname"] = self.pname as AnyObject??
        nillableDictionary["img"] = self.img as AnyObject??
        nillableDictionary["abs"] = self.abs as AnyObject??
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
