//
// ChannelData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChannelData: JSONEncodable {

    /** \u9891\u9053\u540D\u79F0 */
    public var cname: String?
    /** \u662F\u5426\u4E0A\u7EBF */
    public var online: String?
    /** \u9891\u9053ID */
    public var id: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cname"] = self.cname
        nillableDictionary["online"] = self.online
        nillableDictionary["id"] = self.id
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
