//
// ChannelsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ChannelsData: JSONEncodable {
    /** 频道的ID */
    open var id: Int32?
    /** 频道的名称 */
    open var cname: String?
    /** 频道状态 */
    open var state: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["cname"] = self.cname as AnyObject??
        nillableDictionary["state"] = self.state?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
