//
// ChannelsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChannelsData: JSONEncodable {

    /** \u9891\u9053\u7684\u540D\u79F0 */
    public var cname: String?
    /** \u9891\u9053\u7684ID */
    public var id: Int?
    /** \u9891\u9053\u72B6\u6001 */
    public var state: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cname"] = self.cname
        nillableDictionary["id"] = self.id
        nillableDictionary["state"] = self.state
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
