//
// CommentsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CommentsData: JSONEncodable {
    /** 评论ID */
    open var id: Int32?
    /** 评论正文 */
    open var content: String?
    /** 赞数 */
    open var commend: Int32?
    /** 创建时间 */
    open var ctime: String?
    /** 创建该评论的用户ID */
    open var uid: Int32?
    /** 创建该评论的用户名 */
    open var uname: String?
    /** 评论头像 */
    open var avatar: String?
    /** 该评论对应的新闻 docid */
    open var docid: String?
    /** 用户是否能对该条评论点赞，0、1 对应 可点、不可点 */
    open var upflag: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["content"] = self.content as AnyObject??
        nillableDictionary["commend"] = self.commend?.encodeToJSON()
        nillableDictionary["ctime"] = self.ctime as AnyObject??
        nillableDictionary["uid"] = self.uid?.encodeToJSON()
        nillableDictionary["uname"] = self.uname as AnyObject??
        nillableDictionary["avatar"] = self.avatar as AnyObject??
        nillableDictionary["docid"] = self.docid as AnyObject??
        nillableDictionary["upflag"] = self.upflag?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
