//
// CommectCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CommectCreate: JSONEncodable {
    /** 评论内容 */
    open var content: String?
    /** 点赞的数目 */
    open var commend: Int32?
    /** 创建评论时间 */
    open var ctime: String?
    /** 用户ID */
    open var uid: Int32?
    /** 用户名称 */
    open var uname: String?
    /** 用户头像 */
    open var avatar: String?
    /** 评论链接 */
    open var docid: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["content"] = self.content as AnyObject??
        nillableDictionary["commend"] = self.commend?.encodeToJSON()
        nillableDictionary["ctime"] = self.ctime as AnyObject??
        nillableDictionary["uid"] = self.uid?.encodeToJSON()
        nillableDictionary["uname"] = self.uname as AnyObject??
        nillableDictionary["avatar"] = self.avatar as AnyObject??
        nillableDictionary["docid"] = self.docid as AnyObject??
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
