//
// NewinfoData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class NewinfoData: JSONEncodable {
    /** 新闻的ID */
    open var nid: Int64?
    /** 新闻的原地址 */
    open var url: String?
    /** 用户评论信息地址 */
    open var docid: String?
    /** 新闻标题 */
    open var title: String?
    /** 新闻发生时间 */
    open var ptime: String?
    /** 来源名称 */
    open var pname: String?
    /** 新闻来源地址 */
    open var purl: String?
    /** 频道ID */
    open var channel: Int32?
    /** 收藏数 */
    open var collect: Int32?
    /** 关心数 */
    open var concern: Int32?
    /** 评论数目 */
    open var comment: Int32?
    /** 什么玩意的数目 */
    open var inum: Int32?
    /** 新闻的标签列表 */
    open var tags: [String]?
    /** 新闻的内容 */
    open var content: [NewinfoDataContent]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nid"] = self.nid?.encodeToJSON()
        nillableDictionary["url"] = self.url as AnyObject??
        nillableDictionary["docid"] = self.docid as AnyObject??
        nillableDictionary["title"] = self.title as AnyObject??
        nillableDictionary["ptime"] = self.ptime as AnyObject??
        nillableDictionary["pname"] = self.pname as AnyObject??
        nillableDictionary["purl"] = self.purl as AnyObject??
        nillableDictionary["channel"] = self.channel?.encodeToJSON()
        nillableDictionary["collect"] = self.collect?.encodeToJSON()
        nillableDictionary["concern"] = self.concern?.encodeToJSON()
        nillableDictionary["comment"] = self.comment?.encodeToJSON()
        nillableDictionary["inum"] = self.inum?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["content"] = self.content?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
