//
// NewinfoDataContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class NewinfoDataContent: JSONEncodable {
    open var txt: String?
    open var img: String?
    open var vid: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["txt"] = self.txt as AnyObject??
        nillableDictionary["img"] = self.img as AnyObject??
        nillableDictionary["vid"] = self.vid as AnyObject??
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
