//
// NewinfoDataContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NewinfoDataContent: JSONEncodable {

    public var vid: String?
    public var txt: String?
    public var img: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["vid"] = self.vid
        nillableDictionary["txt"] = self.txt
        nillableDictionary["img"] = self.img
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
