//
// NewsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class NewsData: JSONEncodable {

    /** \u65B0\u95FB\u6765\u6E90\u540D\u79F0 */
    public var pubName: String?
    /** \u56FE\u7247\u4E2A\u6570\u7C7B\u578B */
    public var imgStyle: Int?
    /** \u65B0\u95FB\u4F4D\u7F6E\uFF1A\u57CE\u5E02 */
    public var city: String?
    /** \u4EC0\u4E48\u51E0\u628A\u73A9\u610F */
    public var docid: String?
    /** \u4E0A\u7EBF\u65F6\u95F4 */
    public var pubTime: String?
    /** \u65B0\u95FB\u6807\u9898 */
    public var title: String?
    /** \u65B0\u95FB\u539F\u59CB\u5730\u5740 */
    public var url: String?
    /** \u6765\u6E90\u7684URl\u5730\u5740 */
    public var pubUrl: String?
    /** \u65B0\u95FB\u4F4D\u7F6E\uFF1A\u7701\u4EFD */
    public var province: String?
    /** \u8BC4\u8BBA\u4E2A\u6570 */
    public var commentsCount: Int?
    /** \u65B0\u95FB\u4F4D\u7F6E\uFF1A\u533A */
    public var district: String?
    /** \u65B0\u95FB\u539F\u59CB\u5730\u5740 */
    public var channelId: Int?
    /** \u65B0\u95FB\u539F\u59CB\u5730\u5740 */
    public var imgList: [String]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["pubName"] = self.pubName
        nillableDictionary["imgStyle"] = self.imgStyle
        nillableDictionary["city"] = self.city
        nillableDictionary["docid"] = self.docid
        nillableDictionary["pubTime"] = self.pubTime
        nillableDictionary["title"] = self.title
        nillableDictionary["url"] = self.url
        nillableDictionary["pubUrl"] = self.pubUrl
        nillableDictionary["province"] = self.province
        nillableDictionary["commentsCount"] = self.commentsCount
        nillableDictionary["district"] = self.district
        nillableDictionary["channelId"] = self.channelId
        nillableDictionary["imgList"] = self.imgList?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
