//
// UserRegister.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserRegister: JSONEncodable {
    /** 游客ID ， 注册第三方用户的时候，必须本季已经存在一个游客的时候。 */
    open var muid: Int32?
    /** 三方用户相互合并时提供对应的三方用户ID */
    open var msuid: String?
    /** 用户类型注释1.本地注册用户 2游客用户 3微博用户 4微信用户 */
    open var utype: Int32?
    /** 用户平台注释 1.IOS 2安卓 3网页 4无法识别 */
    open var platform: Int32?
    /** 三方用户ID */
    open var suid: String?
    /** 三方用户Token */
    open var stoken: String?
    /** 三房token 过期时间 */
    open var sexpires: String?
    /** 用户名称 */
    open var uname: String?
    /** 用户性别 */
    open var gender: Int32?
    /** 用户头像 */
    open var avatar: String?
    /** 用户的不喜欢的标签列表 */
    open var averse: [String]?
    /** 用户的喜欢的标签列表 */
    open var prefer: [String]?
    /** 用户注册时所在的省份 */
    open var province: String?
    /** 用户注册时所在的城市 */
    open var city: String?
    /** 用户注册时所在的市区 */
    open var district: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["muid"] = self.muid?.encodeToJSON()
        nillableDictionary["msuid"] = self.msuid as AnyObject??
        nillableDictionary["utype"] = self.utype?.encodeToJSON()
        nillableDictionary["platform"] = self.platform?.encodeToJSON()
        nillableDictionary["suid"] = self.suid as AnyObject??
        nillableDictionary["stoken"] = self.stoken as AnyObject??
        nillableDictionary["sexpires"] = self.sexpires as AnyObject??
        nillableDictionary["uname"] = self.uname as AnyObject??
        nillableDictionary["gender"] = self.gender?.encodeToJSON()
        nillableDictionary["avatar"] = self.avatar as AnyObject??
        nillableDictionary["averse"] = self.averse?.encodeToJSON()
        nillableDictionary["prefer"] = self.prefer?.encodeToJSON()
        nillableDictionary["province"] = self.province as AnyObject??
        nillableDictionary["city"] = self.city as AnyObject??
        nillableDictionary["district"] = self.district as AnyObject??
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
