//
// UserData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserData: JSONEncodable {
    /** 用户的类型 */
    open var utype: Int32?
    /** 用户的id 唯一标示 */
    open var uid: Int32?
    /** 用户名称 */
    open var uname: String?
    /** 用户头像 */
    open var avatar: String?
    /** 用户的 token */
    open var password: String?
    /** 用户的频道列表 */
    open var channel: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["utype"] = self.utype?.encodeToJSON()
        nillableDictionary["uid"] = self.uid?.encodeToJSON()
        nillableDictionary["uname"] = self.uname as AnyObject??
        nillableDictionary["avatar"] = self.avatar as AnyObject??
        nillableDictionary["password"] = self.password as AnyObject??
        nillableDictionary["channel"] = self.channel?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
