//
// UserRegister.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserRegister: JSONEncodable {

    /** \u6E38\u5BA2ID \uFF0C \u6CE8\u518C\u7B2C\u4E09\u65B9\u7528\u6237\u7684\u65F6\u5019\uFF0C\u5FC5\u987B\u672C\u5B63\u5DF2\u7ECF\u5B58\u5728\u4E00\u4E2A\u6E38\u5BA2\u7684\u65F6\u5019\u3002 */
    public var muid: Int?
    /** \u4E09\u65B9\u7528\u6237\u76F8\u4E92\u5408\u5E76\u65F6\u63D0\u4F9B\u5BF9\u5E94\u7684\u4E09\u65B9\u7528\u6237ID */
    public var msuid: String?
    /** \u7528\u6237\u7C7B\u578B\u6CE8\u91CA1.\u672C\u5730\u6CE8\u518C\u7528\u6237 2\u6E38\u5BA2\u7528\u6237 3\u5FAE\u535A\u7528\u6237 4\u5FAE\u4FE1\u7528\u6237 */
    public var utype: String?
    /** \u7528\u6237\u5E73\u53F0\u6CE8\u91CA 1.IOS 2\u5B89\u5353 3\u7F51\u9875 4\u65E0\u6CD5\u8BC6\u522B */
    public var platform: Int?
    /** \u4E09\u65B9\u7528\u6237ID */
    public var suid: String?
    /** \u4E09\u65B9\u7528\u6237Token */
    public var stoken: String?
    /** \u4E09\u623Ftoken \u8FC7\u671F\u65F6\u95F4 */
    public var sexpires: String?
    /** \u7528\u6237\u540D\u79F0 */
    public var uname: String?
    /** \u7528\u6237\u6027\u522B */
    public var gender: Int?
    /** \u7528\u6237\u5934\u50CF */
    public var avatar: String?
    /** \u7528\u6237\u7684\u4E0D\u559C\u6B22\u7684\u6807\u7B7E\u5217\u8868 */
    public var averse: [String]?
    /** \u7528\u6237\u7684\u559C\u6B22\u7684\u6807\u7B7E\u5217\u8868 */
    public var prefer: [String]?
    /** \u7528\u6237\u6CE8\u518C\u65F6\u6240\u5728\u7684\u7701\u4EFD */
    public var province: String?
    /** \u7528\u6237\u6CE8\u518C\u65F6\u6240\u5728\u7684\u57CE\u5E02 */
    public var city: String?
    /** \u7528\u6237\u6CE8\u518C\u65F6\u6240\u5728\u7684\u5E02\u533A */
    public var district: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["muid"] = self.muid
        nillableDictionary["msuid"] = self.msuid
        nillableDictionary["utype"] = self.utype
        nillableDictionary["platform"] = self.platform
        nillableDictionary["suid"] = self.suid
        nillableDictionary["stoken"] = self.stoken
        nillableDictionary["sexpires"] = self.sexpires
        nillableDictionary["uname"] = self.uname
        nillableDictionary["gender"] = self.gender
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["averse"] = self.averse?.encodeToJSON()
        nillableDictionary["prefer"] = self.prefer?.encodeToJSON()
        nillableDictionary["province"] = self.province
        nillableDictionary["city"] = self.city
        nillableDictionary["district"] = self.district
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
