//
// UserData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserData: JSONEncodable {

    /** \u7528\u6237\u7684id \u552F\u4E00\u6807\u793A */
    public var uid: Int?
    /** \u7528\u6237\u7684 token */
    public var password: String?
    /** \u7528\u6237\u540D\u79F0 */
    public var uname: String?
    /** \u7528\u6237\u7684\u7C7B\u578B */
    public var utype: Int?
    /** \u7528\u6237\u7684\u9891\u9053\u5217\u8868 */
    public var channel: [String]?
    /** \u7528\u6237\u5934\u50CF */
    public var avatar: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["uid"] = self.uid
        nillableDictionary["password"] = self.password
        nillableDictionary["uname"] = self.uname
        nillableDictionary["utype"] = self.utype
        nillableDictionary["channel"] = self.channel?.encodeToJSON()
        nillableDictionary["avatar"] = self.avatar
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
