//
// VisitorsLogin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class VisitorsLogin: JSONEncodable {

    /** \u7528\u6237\u7684ID */
    public var uid: Int?
    /** \u7528\u6237\u767B\u5F55\u5BC6\u7801 */
    public var password: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["uid"] = self.uid
        nillableDictionary["password"] = self.password
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
