//
// VisitorsRegister.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class VisitorsRegister: JSONEncodable {
    /** 用户类型注释1.本地注册用户 2游客用户 3微博用户 4微信用户 */
    open var utype: Int32?
    /** 用户平台注释 1.IOS 2安卓 3网页 4无法识别 */
    open var platform: Int32?
    /** 用户注册时所在的省份 */
    open var province: String?
    /** 用户注册时所在的城市 */
    open var city: String?
    /** 用户注册时所在的市区 */
    open var district: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["utype"] = self.utype?.encodeToJSON()
        nillableDictionary["platform"] = self.platform?.encodeToJSON()
        nillableDictionary["province"] = self.province as AnyObject??
        nillableDictionary["city"] = self.city as AnyObject??
        nillableDictionary["district"] = self.district as AnyObject??
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary as AnyObject
    }
}
